### PR TITLE
Add file icon

### PR DESCRIPTION
**Pull request by GeorchW**
I felt that it's a bit ugly to have no icon for Ansible files.

Before | After
--|--
image | image

### CODE REVIEW

**Review by ganeshrn — APPROVED** [review]

**Comment by priyamsahoo** [comment]
@GeorchW, thanks for pointing it out. We already have an SVG located inside the `images` dir. Kindly update the PR to make use of that rather than adding a new SVG.

**Review by priyamsahoo — DISMISSED** [review]
@GeorchW, thanks for pointing it out. We already have an SVG located at the `images` dir. Kindly update the PR to use that SVG rather than adding a new PNG.

**Comment by GeorchW** [comment]
> We already have an SVG located at the images dir. Kindly update the PR to use that SVG rather than adding a new PNG.

Yes, I used that SVG file and adjusted the margins and the color slightly to fit with the other file icons in VS Code. The original icon is bigger and brighter and thus looks out-of-place. I had a look at it in both dark and light mode, and the adjusted color works for both. (I just had a look at the default dark and light themes, I didn't check every theme there is.)

**Comment by GeorchW** [comment]
@priyamsahoo ping

**Comment by goneri** [comment]
@GeorchW could you please rebase?

**Comment by GeorchW** [comment]
@goneri done

**Comment by goneri** [comment]
Thank you @GeorchW!

**Pull request merged**
