### PR TITLE
Enables reuse of existing ansible terminals

### PR DESCRIPTION
**Pull request by egnirra**
When using vscode commands to run ansible-playbook or ansible-navigator as seen in this image:
image

It will create a new terminal for each time you run the command.
image

Perhaps this is as expected, you want to run multiple playbooks via vscode at the same time, but I would argue it's not the best experience for most use cases.

Another way could be to have an option to enable/disable this behavior?

### CODE REVIEW

**Comment by priyamsahoo** [comment]
@egnirra, this looks good, but as you mentioned, having multiple terminals opened allows the user to run multiple playbooks simultaneously. Could you try to extend this feature to allow users to choose the way they wish to run it?

**Review by ganeshrn — APPROVED** [review]
Thanks for your contribution!

**Review by ssbarnea — APPROVED** [review]

**Review by priyamsahoo — APPROVED** [review]

**Comment by egnirra** [comment]
If I have some time over I will look in to adding the configuration option, can do another PR if you want.

Thanks for the input!

**Comment by ssbarnea** [comment]
@egnirra Take a look on how we implemented the other options, it should be easy for you to add it as configurable.

And, thanks for raising the PR!

**Pull request merged**
