### PR TITLE
AAP-26820: Task not found in ARI postprocess results

### PR DESCRIPTION
**Pull request by romartin**
Hey @TamiTakamiya 

Please see https://issues.redhat.com/browse/AAP-26820

This PR ensures that lightspeed is not triggered in case the prompt is not for a "task" context, for task files.  
For more info, plse see my latest comment on the ticket https://issues.redhat.com/browse/AAP-26820 

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
hmm my new tests are not running... that's why it complains about coverage, looking....

**Comment by romartin** [comment]
tests running now!

**Review by TamiTakamiya — APPROVED** [review]
Honestly I may not fully understand the original logic yet, I understand the intention of this PR and changes look good with the test cases. Thanks for picking up this complicated issue!

**Comment by romartin** [comment]
Rebased.

Not sure why it complains about coverage, because running the tests locally I got the right coverage, by running the new test cases being included in this PR. Anyway, as discussed with @TamiTakamiya , we can go ahead with it once CI runs succuessful.

Thanks!

**Comment by romartin** [comment]
Now the CI pipeline worked well, merged.

**Pull request merged**
