### PR TITLE
LightspeedExplorer view as a Webview and new button

### PR DESCRIPTION
**Pull request by goneri**
Convert the "Ansible Lighspeed Login" panel from a TreeView to a WebView. The goal is to be able to expose an addition button icon.
    
This commit also adds a new "Explain the current playbook" button to this view to trigger a playbook explanation.

### CODE REVIEW

**Review by TamiTakamiya — CHANGES_REQUESTED** [review]
1. A UI test case "Verify the presence of lightspeed login button in the activity bar"  is broken even though VS Code extension UI tests are not integreated into CI pipeline yet. If you open a new ticket for that part, I think we can work on this issue later.
2. Though it The "Explain the current playbook" button opens a new "Explain" editor tab even when the "Explain" tab already exists for the same playbook. We may want to address this issue in a separate ticket as there are some more complicated situations, like when there are more than one "Explain" tabs for multiple playbooks.

**Comment by goneri** [comment]
> 2\. Though it The "Explain the current playbook" button opens a new "Explain" editor tab even when the "Explain" tab already exists for the same playbook. We may want to address this issue in a separate ticket as there are some more complicated situations, like when there are more than one "Explain" tabs for multiple playbooks.

Yes, I agree, this one is not specific to this PR and should be address in a different PR.

**Comment by goneri** [comment]
`Verify the presence of lightspeed login button in the activity bar` is only broken with `1.85.2` and this is reproductible with the `main` branch.

**Comment by TamiTakamiya** [comment]
I found [a relatively new issue](https://github.com/redhat-developer/vscode-extension-tester/pull/1002) on vscode-extension-tester, which was closed in November 2023. It looks like accessing to a webview on the sidebar requires a different class (`WebviewView`) for vscode-extension-tester. Let me try to modify the test code using the `WebviewView` class.

**Comment by TamiTakamiya** [comment]
@goneri Would you take a look at [the UI test fix commited to my fork](https://github.com/ansible/vscode-ansible/commit/cfd9cd8a7f6d0eae01183f76fd125687293e8b82)? Test cases were modified with the `WebviewView` class for accessing the new Webview on Sidebar. Thanks.

**Comment by goneri** [comment]
@TamiTakamiya  I just cherry-picked cfd9cd8a7f6d0eae01183f76fd125687293e8b82 and force-pushed my branch with it.

**Comment by goneri** [comment]
I end up with a different error: `/home/runner/work/vscode-ansible/vscode-ansible/test/ui-test/lightspeedUiTest.ts:25:9: 'lightspeedServiceSection' is assigned a value but never used. [Error/@typescript-eslint/no-unused-vars]

**Comment by goneri** [comment]
Superseded by https://github.com/ansible/vscode-ansible/pull/1235

**Pull request closed without merging**
