### PR TITLE
fix: update compile withserver script

### PR DESCRIPTION
**Pull request by ganeshrn**
Update the `compile:withserver` script to create a soft
link in the `out/sever` folder for `node_modules` directory
of `ansible-language-server` to handle new package
depedency added in the language-server code while setting
up development environment

### CODE REVIEW

**Comment by priyamsahoo** [comment]
LGTM !

**Review by priyamsahoo — APPROVED** [review]
LGTM !

**Comment by ssbarnea** [comment]
@ganeshrn Are we going to support development of this extension under Windows? Does `ln` work under WSL? Asking because we already have a Windows jobs for the language server, known to be broken.

If we do not support development we will need to setup jobs that only install the already built extension artifact and test it under Windows, a bit more complex pipeline but doable.

If we consider that as a supported use case, I would prefer not to deepen the breakage. I personally do not use Windows at all, so I am ok with each path.

**Comment by matburt** [comment]
If you are staying in wsl, everything works the way you would expect it to:

image

It works best if you aren't crossing the filesystem boundary into Windows. The file will exist it probably just won't be usable:

image

This is a familiar pattern to WSL users and the WSL Remote capability in VSCode also follows this pattern. Users of that remote will also understand it well.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
