### PR TITLE
Added initial README for Tests.

### PR DESCRIPTION
**Pull request by omaciel**
Initial documentation for running automated test suites.

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Comment by manstis** [comment]
This is what I find hard to understand...

The tests on this PR fail whereas they pass on https://github.com/ansible/vscode-ansible/pull/1370

@TamiTakamiya @goneri Are tests in this repository notoriously flakey?

**Comment by manstis** [comment]
@omaciel You need to add a label for the `ack / ack / ack` action to pass.

**Comment by omaciel** [comment]
Thank you @manstis I saw the error but I don't seem to have the right access to add labels :/

**Review by ganeshrn — APPROVED** [review]
Thank you!

**Comment by ganeshrn** [comment]
@omaciel I have added you in the `teams/lightspeed-ansible-vscode` team, so you should have the required access.

**Comment by omaciel** [comment]
Thank you @ganeshrn

**Pull request merged**
