### PR TITLE
Fix creator folder opening

### PR DESCRIPTION
**Pull request by priyamsahoo**
Adds the ability to open the workspace folder after scaffolding is done based on the workspace folder count. This resolves the issue of ansible-creator scaffolding not working when used multiple times.
Fixes: #1217.

### CODE REVIEW

**Review by shatakshiiii — APPROVED** [review]

**Review by ganeshrn — APPROVED** [review]

**Comment by omaciel** [comment]
Will there be tests added/updated as part of this PR?

**Comment by ganeshrn** [comment]
> Will there be tests added/updated as part of this PR?

That's a good catch, the coverage is reduced by 0.2%. @priyamsahoo Can you please add test cases to this PR.

**Comment by priyamsahoo** [comment]
@omaciel, @ganeshrn, as of now, there are no tests for the ansible-creator scaffolding features. I am in the process of adding the tests (One of the PRs in this process is https://github.com/ansible/vscode-ansible/pull/1318). I should add the tests of all these together in the subsequent PRs.

**Comment by omaciel** [comment]
@priyamsahoo I don't want to introduce changes to your existing processes... yet ;) but I think it would give your PR a major boost of confidence if the tests were part of it

**Comment by priyamsahoo** [comment]
In that case, this PR has to wait for a week or two before I set up the testing framework for Ansible content creator web views in the extension (which is currently nonexistent).

**Comment by omaciel** [comment]
@priyamsahoo sounds like a great opportunity to handle an existing technical debt then?

**Pull request merged**
